### GET single store by category_id and id
GET http://localhost:4000/api/store/1

### GET all stores by category
GET http://localhost:4000/api/store?categoryId=3&offset=0&limit=10

### Get menu of store
GET http://localhost:4000/api/store/1/menu